export enum tagTypes {
  student = 'student',
  FileList = 'FileList',
  Faq = 'Faq',
  FriendShip = 'FriendShip',
  announcement = 'announcement',
  TeacherAccessCoursey = 'TeacherAccessCoursey',
  assignment = 'assignment',
  submitassignment = 'submitassignment',
  deleteAssignment = 'deleteAssignment',
  user = 'user',
  moderator = 'moderator',
  admin = 'admin',
  trainer = 'trainer',
  category = 'category',
  milestone = 'milestone',
  ChatMessage = 'ChatMessage',
  module = 'module',
  lesson = 'lesson',
  quiz = 'quiz',
  course = 'course',
  service = 'service',
  booking = 'booking',
  glossary = 'glossary',
  faq = 'faq',
  rating = 'rating',
  resource = 'resource',
  categoryChildren = 'categoryChildren',
  submitQuiz = 'submitQuiz',
  package = 'package',
  userPurchaseCourse = 'userPurchaseCourse',
  userPurchaseCategory = 'userPurchaseCategory',
  addPackageAndcourseTag = 'addPackageAndcourseTag',
  LoginHistory = 'LoginHistory',
  profile = 'profile',
  cart = 'cart',
  ShowAdvanceClasses = 'ShowAdvanceClasses',
  Skills_plan = 'Skills_plan',
  overview = 'overview',
  contact = 'contact',
  course_label = 'course_label',
  seller = 'seller',
  Member = 'Member',
}

export const tagTypesList = [
  tagTypes.ChatMessage,
  tagTypes.FileList,
  tagTypes.Faq,
  tagTypes.FriendShip,
  tagTypes.announcement,
  tagTypes.deleteAssignment,
  tagTypes.seller,
  tagTypes.submitassignment,
  tagTypes.assignment,
  tagTypes.category,
  tagTypes.student,
  tagTypes.user,
  tagTypes.moderator,
  tagTypes.admin,
  tagTypes.trainer,
  tagTypes.milestone,
  tagTypes.module,
  tagTypes.lesson,
  tagTypes.quiz,
  tagTypes.faq,
  tagTypes.service,
  tagTypes.rating,
  tagTypes.rating,
  tagTypes.course,
  tagTypes.resource,
  tagTypes.glossary,
  tagTypes.categoryChildren,
  tagTypes.submitQuiz,

  tagTypes.package,
  tagTypes.userPurchaseCourse,
  tagTypes.userPurchaseCategory,
  tagTypes.addPackageAndcourseTag,
  tagTypes.LoginHistory,
  tagTypes.profile,
  tagTypes.cart,
  tagTypes.ShowAdvanceClasses,
  tagTypes.Skills_plan,
  tagTypes.overview,
  tagTypes.contact,
  tagTypes.course_label,
  tagTypes.Member,
  tagTypes.TeacherAccessCoursey,
];
