name: CLIENT

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect dependency-related changes
        id: deps_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            dependencies:
              - 'package.json'
              - 'yarn.lock'

      - name: Install Dependencies
        # Uncomment the line below if you want to skip this step unless deps changed
        # if: steps.deps_changes.outputs.dependencies == 'true'
        run: yarn install

      - name: Replace .env with production version
        run: cp -f .env.live .env.local

      - name: Build the project in a temporary folder
        run: |
          echo "Starting safe build..."
          rm -rf .next_temp
          NEXT_PUBLIC_ENV=production yarn build
          mv .next .next_old || true
          mv .next_temp .next

      - name: Restart or Start PM2 process
        run: |
          if pm2 list | grep -q "education-client"; then
            echo "Restarting education-client..."
            pm2 reload education-client --update-env
          else
            echo "Starting education-client..."
            pm2 start ecosystem.config.js --env production
          fi

      - name: Clean up old build
        run: rm -rf .next_old
